name: test

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Install poetry
      run: |
        curl -sSL \
          "https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py" | python
    - name: Set up cache
      uses: actions/cache@v1
      with:
        path: .venv
        key: venv-${{ hashFiles('poetry.lock') }}
    - name: Install dependencies
      run: |
        source "$HOME/.poetry/env"
        poetry config virtualenvs.in-project true
        poetry install
    - name: Run code quality checks
      run: |
        source "$HOME/.poetry/env"
        poetry check
        poetry run pip check
        poetry run flake8 .
        poetry run mypy .
        poetry run safety check --full-report
    - name: Run pytest
      run: |
        source "$HOME/.poetry/env"
        poetry run pytest .
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        file: ./coverage.xml
